using ResQ.API.DTOs.Orders;

namespace ResQ.API.DTOs.Admin;

/// <summary>
/// Row in the admin merchant-management list, summarising one merchant's identity,
/// status, Mercado Pago connection, and headline performance metrics.
/// </summary>
public class AdminMerchantListItemResponse
{
    /// <summary>Merchant profile ID.</summary>
    public int Id { get; set; }

    /// <summary>Public business name.</summary>
    public string BusinessName { get; set; } = string.Empty;

    /// <summary>Argentine tax ID (CUIT) of the business.</summary>
    public string Cuit { get; set; } = string.Empty;

    /// <summary>Login email of the owning user account.</summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>Whether the owning user account is active (can log in and operate).</summary>
    public bool IsActive { get; set; }

    /// <summary>Mercado Pago connection status (e.g. "Connected", "Disconnected").</summary>
    public string MpConnectionStatus { get; set; } = string.Empty;

    /// <summary>Food categories assigned to the merchant.</summary>
    public List<string> Categories { get; set; } = [];

    /// <summary>Total completed orders all time.</summary>
    public int TotalOrders { get; set; }

    /// <summary>Total platform revenue generated by this merchant all time.</summary>
    public decimal TotalRevenue { get; set; }

    /// <summary>Average rating across all reviews.</summary>
    public decimal AverageRating { get; set; }

    /// <summary>When the merchant registered.</summary>
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// Full admin detail view of a single merchant: identity and contact data, performance
/// metrics, the most recent orders, and the Mercado Pago token-refresh log history.
/// </summary>
public class AdminMerchantDetailResponse
{
    /// <summary>Merchant profile ID.</summary>
    public int Id { get; set; }

    /// <summary>Public business name.</summary>
    public string BusinessName { get; set; } = string.Empty;

    /// <summary>Argentine tax ID (CUIT).</summary>
    public string Cuit { get; set; } = string.Empty;

    /// <summary>Login email of the owning user account.</summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>Street address of the merchant location.</summary>
    public string Address { get; set; } = string.Empty;

    /// <summary>Public contact phone.</summary>
    public string ContactPhone { get; set; } = string.Empty;

    /// <summary>Whether the owning user account is active.</summary>
    public bool IsActive { get; set; }

    /// <summary>Mercado Pago connection status.</summary>
    public string MpConnectionStatus { get; set; } = string.Empty;

    /// <summary>Food categories assigned to the merchant.</summary>
    public List<string> Categories { get; set; } = [];

    /// <summary>Total completed orders all time.</summary>
    public int TotalOrders { get; set; }

    /// <summary>Total GMV generated all time.</summary>
    public decimal TotalGmv { get; set; }

    /// <summary>Total platform revenue generated all time.</summary>
    public decimal TotalRevenue { get; set; }

    /// <summary>Average rating across all reviews.</summary>
    public decimal AverageRating { get; set; }

    /// <summary>Total reviews received.</summary>
    public int ReviewCount { get; set; }

    /// <summary>Number of currently active packs.</summary>
    public int ActivePacks { get; set; }

    /// <summary>When the merchant registered.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>The 10 most recent orders received by this merchant.</summary>
    public List<MerchantOrderSummaryResponse> RecentOrders { get; set; } = [];

    /// <summary>The Mercado Pago token-refresh log entries for this merchant, newest first.</summary>
    public List<MpRefreshLogResponse> MpRefreshLogs { get; set; } = [];
}

/// <summary>One Mercado Pago token-refresh audit log entry for the admin merchant detail view.</summary>
/// <param name="Success">Whether the refresh succeeded.</param>
/// <param name="ErrorMessage">Failure detail when unsuccessful; otherwise null.</param>
/// <param name="CreatedAt">When the refresh attempt ran.</param>
public record MpRefreshLogResponse(bool Success, string? ErrorMessage, DateTime CreatedAt);
