using ResQ.API.Models.Auth;
using ResQ.API.Models.Common;
using ResQ.API.Models.Enums;
using ResQ.API.Models.Orders;

namespace ResQ.API.Models.Notifications;

/// <summary>
/// Represents an in-app notification surfaced to a merchant in their panel header bell.
/// Notifications are generated by domain events (a paid order, a cancelled order) so the
/// merchant does not need to keep polling the orders panel to learn about new activity.
/// </summary>
public class MerchantNotification : BaseEntity
{
    /// <summary>
    /// Foreign key referencing the <see cref="MerchantProfile"/> this notification belongs to.
    /// Every query is scoped by this value to prevent cross-merchant access.
    /// </summary>
    public int MerchantId { get; set; }

    /// <summary>
    /// The kind of event that produced this notification, used by the frontend to choose
    /// an icon and styling.
    /// </summary>
    public NotificationType Type { get; set; }

    /// <summary>
    /// Short headline shown in bold at the top of the notification row.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable body text describing the event (e.g. the pack name and amount).
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// Whether the merchant has already read this notification. Drives the unread badge count
    /// and the visual highlight on unread rows.
    /// </summary>
    public bool IsRead { get; set; }

    /// <summary>
    /// Optional foreign key referencing the <see cref="Order"/> that triggered the notification,
    /// allowing the frontend to deep-link to the relevant order. Null for notifications not tied
    /// to a specific order. The order is never cascade-deleted to preserve accounting integrity.
    /// </summary>
    public int? OrderId { get; set; }

    /// <summary>
    /// Navigation property to the merchant who owns this notification.
    /// </summary>
    public MerchantProfile Merchant { get; set; } = null!;

    /// <summary>
    /// Navigation property to the order that triggered this notification, if any.
    /// </summary>
    public Order? Order { get; set; }
}
