using ResQ.API.Models.Auth;
using ResQ.API.Models.Common;
using ResQ.API.Models.Enums;
using ResQ.API.Models.Reviews;

namespace ResQ.API.Models.Orders;

/// <summary>
/// Represents a consumer's purchase transaction on the ResQ platform.
/// An order is created when a consumer initiates checkout, progresses through payment
/// via Mercado Pago, and is finalised when the consumer picks up their Surprise Pack
/// at the merchant's location using the <see cref="PickupCode"/>.
/// Financial records are never cascade-deleted to preserve accounting integrity.
/// </summary>
public class Order : BaseEntity
{
    /// <summary>
    /// Foreign key referencing the <see cref="ConsumerProfile"/> that placed this order.
    /// </summary>
    public int ConsumerId { get; set; }

    /// <summary>
    /// Foreign key referencing the <see cref="MerchantProfile"/> from whom the order was placed.
    /// </summary>
    public int MerchantId { get; set; }

    /// <summary>
    /// The total monetary amount charged to the consumer, in Argentine pesos (ARS).
    /// Equals the sum of all <see cref="OrderDetail"/> line items.
    /// </summary>
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// The portion of <see cref="TotalAmount"/> retained by the ResQ platform as a service fee,
    /// collected via Mercado Pago's marketplace fee mechanism.
    /// </summary>
    public decimal PlatformFee { get; set; }

    /// <summary>
    /// The net amount credited to the merchant after the <see cref="PlatformFee"/> is deducted.
    /// Equal to <see cref="TotalAmount"/> minus <see cref="PlatformFee"/>.
    /// </summary>
    public decimal MerchantEarnings { get; set; }

    /// <summary>
    /// A UUID generated by the platform and sent to Mercado Pago as the <c>external_reference</c>
    /// field when creating the payment preference. When MP delivers a payment webhook, this value
    /// is used to correlate the notification with the correct internal order record.
    /// </summary>
    public string ExternalReference { get; set; } = string.Empty;

    /// <summary>
    /// The Mercado Pago payment preference identifier returned by the MP Preferences API.
    /// Used to redirect the consumer to the MP checkout page. Null before the preference is created.
    /// </summary>
    public string? MpPreferenceId { get; set; }

    /// <summary>
    /// The Mercado Pago payment identifier assigned once the consumer completes payment.
    /// Populated from the webhook payload. Null while the order is still pending.
    /// </summary>
    public long? MpPaymentId { get; set; }

    /// <summary>
    /// The current lifecycle state of the order (Pending, Paid, PickedUp, or Cancelled).
    /// Transitions are driven by Mercado Pago webhooks and merchant pickup confirmation.
    /// </summary>
    public OrderStatus OrderStatus { get; set; } = OrderStatus.Pending;

    /// <summary>
    /// A 6-character alphanumeric code shown to the consumer in the app after successful payment.
    /// The merchant scans or manually enters this code to confirm pickup and complete the order.
    /// Generated server-side when the payment webhook is processed.
    /// </summary>
    public string PickupCode { get; set; } = string.Empty;

    /// <summary>
    /// Navigation property to the consumer who placed this order.
    /// </summary>
    public ConsumerProfile Consumer { get; set; } = null!;

    /// <summary>
    /// Navigation property to the merchant who fulfilled (or is due to fulfil) this order.
    /// </summary>
    public MerchantProfile Merchant { get; set; } = null!;

    /// <summary>
    /// The individual product line items that make up this order.
    /// </summary>
    public ICollection<OrderDetail> OrderDetails { get; set; } = [];

    /// <summary>
    /// The consumer's review of the merchant submitted after a completed order.
    /// Null if the consumer has not yet left a review for this order.
    /// </summary>
    public Review? Review { get; set; }
}
