using System.Text.Json.Serialization;

namespace ResQ.API.Services.MercadoPago;

// Internal records used for MP REST API serialization/deserialization.
// Not exposed to controllers or clients.

/// <summary>
/// Request body sent to <c>POST /checkout/preferences</c> to create a Mercado Pago
/// Checkout Pro preference for a consumer order.
/// </summary>
/// <param name="Items">List of items included in this checkout preference (one per pack line).</param>
/// <param name="MarketplaceFee">
/// The platform commission (in ARS) that ResQ collects on each transaction.
/// Automatically deducted from the payment and credited to the ResQ marketplace account.
/// </param>
/// <param name="ExternalReference">
/// A UUID generated by ResQ and stored on the <c>Orders</c> row. Used as the
/// correlation key when the payment webhook arrives to identify the matching order.
/// </param>
/// <param name="BackUrls">URLs to redirect the consumer after payment success, failure, or pending state.</param>
/// <param name="AutoReturn">
/// Controls automatic redirect after payment. Set to <c>"approved"</c> to redirect
/// only on success, or <c>"all"</c> to redirect for every outcome.
/// </param>
/// <param name="NotificationUrl">
/// The ResQ webhook endpoint URL that Mercado Pago calls with payment status updates.
/// Must be publicly accessible (not localhost).
/// </param>
internal sealed record MpPreferenceRequest(
    [property: JsonPropertyName("items")]              List<MpItem>    Items,
    [property: JsonPropertyName("marketplace_fee")]    decimal         MarketplaceFee,
    [property: JsonPropertyName("external_reference")] string          ExternalReference,
    [property: JsonPropertyName("back_urls")]          MpBackUrls      BackUrls,
    [property: JsonPropertyName("auto_return")]        string          AutoReturn,
    [property: JsonPropertyName("notification_url")]   string          NotificationUrl
);

/// <summary>
/// Represents a single line item within a <see cref="MpPreferenceRequest"/>.
/// Each pack in an order maps to one <see cref="MpItem"/>.
/// </summary>
/// <param name="Title">Display name of the item shown on the Mercado Pago checkout page.</param>
/// <param name="Quantity">Number of units being purchased.</param>
/// <param name="CurrencyId">ISO 4217 currency code. Always <c>"ARS"</c> for Argentine Peso.</param>
/// <param name="UnitPrice">Price per unit in the specified currency.</param>
internal sealed record MpItem(
    [property: JsonPropertyName("title")]       string  Title,
    [property: JsonPropertyName("quantity")]    int     Quantity,
    [property: JsonPropertyName("currency_id")] string  CurrencyId,
    [property: JsonPropertyName("unit_price")]  decimal UnitPrice
);

/// <summary>
/// Redirect URLs sent with a <see cref="MpPreferenceRequest"/> to control where Mercado Pago
/// sends the consumer after each payment outcome.
/// </summary>
/// <param name="Success">Frontend URL to redirect to when the payment is approved.</param>
/// <param name="Failure">Frontend URL to redirect to when the payment fails or is rejected.</param>
/// <param name="Pending">Frontend URL to redirect to when the payment is pending further review.</param>
internal sealed record MpBackUrls(
    [property: JsonPropertyName("success")] string Success,
    [property: JsonPropertyName("failure")] string Failure,
    [property: JsonPropertyName("pending")] string Pending
);

/// <summary>
/// Relevant fields from the Mercado Pago API response to <c>POST /checkout/preferences</c>.
/// Contains the checkout URLs needed to redirect the consumer to the payment page.
/// </summary>
/// <param name="Id">The unique identifier of the created checkout preference.</param>
/// <param name="InitPoint">Live checkout URL. Used in production environments.</param>
/// <param name="SandboxInitPoint">Sandbox checkout URL. Used during development and testing.</param>
internal sealed record MpPreferenceApiResponse(
    [property: JsonPropertyName("id")]                 string Id,
    [property: JsonPropertyName("init_point")]         string InitPoint,
    [property: JsonPropertyName("sandbox_init_point")] string SandboxInitPoint
);

/// <summary>
/// Relevant fields from the Mercado Pago payment resource returned by
/// <c>GET /v1/payments/{id}</c>. Used by <see cref="MpWebhookProcessorService"/>
/// to verify payment status before transitioning an order.
/// </summary>
/// <param name="Id">The Mercado Pago payment ID. Stored on the order after successful processing.</param>
/// <param name="Status">
/// Current payment status as reported by Mercado Pago (e.g., <c>"approved"</c>,
/// <c>"in_process"</c>, <c>"rejected"</c>). Only <c>"approved"</c> triggers an order transition.
/// </param>
/// <param name="ExternalReference">
/// The UUID generated by ResQ and sent as <c>external_reference</c> when creating the
/// checkout preference. Used to correlate this payment with the corresponding ResQ order.
/// </param>
/// <param name="TransactionAmount">Total amount charged to the consumer in ARS.</param>
internal sealed record MpPaymentApiResponse(
    [property: JsonPropertyName("id")]                 long    Id,
    [property: JsonPropertyName("status")]             string  Status,
    [property: JsonPropertyName("external_reference")] string  ExternalReference,
    [property: JsonPropertyName("transaction_amount")] decimal TransactionAmount
);
